#!/usr/bin/env bash

COLOR_DISCHARGING="^c#FF0000^"
COLOR_AC="^c#00FF00^"
COLOR_RESET="^d^"

function battery() {
	if [ -f /usr/bin/acpi ]; then
		ac=$(acpi -a)
		batt=$(acpi -b | sed -e 's/Battery 0: //g' | sed -e 's/Unknown, //g')
		if [[ $ac = "Adapter 0: on-line" ]]; then
			echo "${COLOR_AC}AC power, ${batt}${COLOR_RESET}"
		else
			echo "${COLOR_DISCHARGING}${batt}${COLOR_RESET}"
		fi
	else
		echo "N/A"
	fi
}

function cpu_temp() {
	acpi -t | cut -f 4,6 -d " "
}

function datetime() {
	if [ "$1" = "" ]; then
		TZ=$(cat /etc/timezone) date +"%a %b %d %R %Z"
	else
		TZ=$1 date +"%a %b %d %R %Z"
	fi
}

function freespace() {
	df -h --output=avail "$1" | awk -v thefs="$1" 'NR == 2 { print $1 " free on " thefs }'
}

function identity() {
	echo "$(whoami)@$(hostname)"
}

function kernel() {
	uname -r
}

function os_release() {
	lsb_release -d | cut -f 2
}

function ssid() {
	if [ -f /sbin/iwgetid ]; then
		result="$(/sbin/iwgetid -r )";
		if [ -z "$result" ]; then
				result="N/A";
		fi
	else
		result="N/A";
	fi
	echo "SSID: ${result}"
}

function system_uptime() {
	uptime -p
}

function volume() {
	v=$(amixer sget Master | awk -F"[][]" '/dB/ { print $2 }')
	echo "Vol: ${v}"
}

top="$(battery) | $(cpu_temp) | $(ssid) | $(volume) | $(freespace /) | $(datetime)"
bottom="$(identity) | $(kernel) | $(os_release) | $(system_uptime) | $(datetime Europe/Berlin)"
xsetroot -name "${top};${bottom}"
