#!/usr/bin/env bash

COLOR_DISCHARGING="^c#FF0000^"
COLOR_AC="^c#00FF00^"
COLOR_RESET="^d^"

function battery() {
	if [ -f /usr/bin/acpi ]; then
		ac=$(acpi -a)
		batt=$(acpi -b | sed -e 's/Battery 0: //g' | sed -e 's/Unknown, //g')
		if [[ $ac = "Adapter 0: on-line" ]]; then
			echo "${COLOR_AC}AC power, ${batt}${COLOR_RESET}"
		else
			echo "${COLOR_DISCHARGING}${batt}${COLOR_RESET}"
		fi
	else
		echo "N/A"
	fi
}

function datetime() {
	TZ=$(cat /etc/timezone) date +"%a %b %d %R %Z"
}

function freespace() {
	df -h --output=avail "$1" | awk -v thefs="$1" 'NR == 2 { print $1 " free on " thefs }'
}

function kernel() {
	uname -r
}

function os_release() {
	cat /etc/os-release | grep "PRETTY_NAME" | sed -e 's/PRETTY_NAME=//g; s/"//g'
}

function ssid() {
	if [ -f /sbin/iwgetid ]; then
		result="$(/sbin/iwgetid -r )";
		if [ -z "$result" ]; then
				result="N/A";
		fi
	else
		result="N/A";
	fi
	echo "SSID: ${result}"
}

function system_uptime() {
	uptime -p
}

xsetroot -name "$(battery) | $(system_uptime) | $(ssid) | $(freespace /) | $(datetime);$(kernel) | $(os_release)"
